### PR TITLE
add ability to set options

### PR DESCRIPTION
**Pull request by darrinholst**
I left the default options of NSLayoutFormatAlignAllCenterY and X, just added the ability to override them as they were conflicting with a layout I was trying to do

```
Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint:0x9535c90 h=--- v=--- H:[UIWindow:0x93b0000(320)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x9534640 h=-&- v=-&- UIView:0x95251f0.width == UIWindow:0x93b0000.width>",
    "<NSLayoutConstraint:0x952aa80 H:[UIView:0x95199b0]-(NSSpace(20))-|   (Names: '|':UIView:0x95251f0 )>",
    "<NSLayoutConstraint:0x952aa00 H:|-(NSSpace(20))-[UIView:0x95199b0]   (Names: '|':UIView:0x95251f0 )>",
    "<NSLayoutConstraint:0x952a6f0 H:[UILabel:0x951ecd0(50)]>",
    "<NSLayoutConstraint:0x952a680 H:|-(NSSpace(20))-[UILabel:0x951ecd0]   (Names: '|':UIView:0x95251f0 )>",
    "<NSLayoutConstraint:0x952a320 UILabel:0x951ecd0.centerX == UIView:0x95199b0.centerX>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x952a320 UILabel:0x951ecd0.centerX == UIView:0x95199b0.centerX>
```

### CODE REVIEW

**Comment by qrush** [comment]
Nice. Mind adding an example of this into the readme? Also possibly modifying the Timer example to show how to use this?

**Comment by darrinholst** [comment]
Sure, will put something together tomorrow.

**Comment by darrinholst** [comment]
The first example with the version number is kind of contrived. The second usage in the readme with the warning is the actual reason I needed this. 

I haven't done enough of this to know if the current defaults of `NSLayoutFormatAlignAllCenterY` and `NSLayoutFormatAlignAllCenterX` are actually the common case when you start getting more element relationships.

**Comment by seanlilmateus** [comment]
@darrinholst, I believe you should change the default options to [NSLayoutFormatDirectionLeadingToTrailing](https://developer.apple.com/library/mac/#documentation/AppKit/Reference/NSLayoutConstraint_Class/NSLayoutConstraint/NSLayoutConstraint.html), otherwise it will create a lot of layout ambiguity. 

e.g.: try to create a reset button on the right side of the start button

``` ruby
    Motion::Layout.new do |layout|
      layout.view view
      layout.subviews state: @state, action: @action, reset: @reset
      layout.metrics top: 200, margin: 20, height: 40
      layout.vertical "|-top-[state(==height)]-margin-[action(==height)]"
      layout.vertical "|-top-[state(==height)]-margin-[reset(==height)]"
      layout.horizontal "|-margin-[state]-margin-|"
      layout.horizontal "|-margin-[action]-[reset(==action)]-margin-|"
    end
```

**Comment by darrinholst** [comment]
I'd be fine with not having a default at all. I just used those because they were originally defaulted to that without any way of changing it. 

@qrush thoughts?

**Comment by amiel** [comment]
:+1: I need this as well.

What needs to happen to get this merged?

**Comment by qrush** [comment]
Hey there, I'm looking for a new maintainer for this. Can you check out #13?

**Pull request closed without merging**
